### ISSUE TITLE
Attempt to find solution for app crash in event that no category is selected on new thread form

### ISSUE THREAD

**Issue by BuckG71** [ponyNYC/bridge_2022#23]
## Overview

- research solutions for fixing this bug
- write code that attempts to fix the bug

**Comment by BuckG71** [comment]
Chung added "checked" attribute with default value = True so that all boxes are checked by default. This technically doesn't fix the bug, as the user could uncheck all boxes and press submit, which would still crash the app. Suggest continuing to look for a robust solution to this problem, but this is ok for now

**Comment by Sanlung** [comment]
Please submit a question without checking any categories to see if the app crashes.

A notification to the user that at least one category must be checked for the question to be processed, if can be done within Django and if not with other means, should the next logical step for the imperfection.
